#ifndef DEFINES
#define DEFINES

//--------------------------------------------------------------------------------------
// Constants
//--------------------------------------------------------------------------------------

//KeyboardStatesCount
#define MAX_KEYBOARD_STATES 256

//MAX VERTICES IN VERTEX BUFFER
#define MAX_VERTICES 32766

//MAX WIREFRAMES
#define MAX_WIREFRAMES 65532

//MAX CONTOURS
#define MAX_CONTOURS 65532

//MOUSE BUTTONS
#define MB_LEFT_MOUSE_BUTTON 0
#define MB_RIGHT_MOUSE_BUTTON 1
#define MB_MIDDLE_MOUSE_BUTTON 2

//ResultCode
typedef unsigned short int RC_RESULT;
#define RC_ERROR 0
#define RC_SUCCESS 1

//ProgramTextIndexes
#define PTI_WINDOW_TITLE 0
#define PTI_FILE 1
#define PTI_OPEN_DATABASE 2
#define PTI_SAVE_MODEL 3
#define PTI_NEW_MODEL_OUTSIDE_DATABASE 4
#define PTI_SAVE_MODEL_OUTSIDE_DATABASE 5
#define PTI_LOAD_MODEL_OUTSIDE_DATABASE 6
#define PTI_INSERT_MODEL 7
#define PTI_EXPORT_MODEL 8
#define PTI_CONVERT_PICTURE_TO_MODEL 9
#define PTI_OPTIONS 10
#define PTI_SIZE_OF_MODEL 11
#define PTI_FRAME 12
#define PTI_WIREFRAME 13
#define PTI_RESTORE_VIEW 14
#define PTI_PIPETTE 15
#define PTI_LANGUAGE 16
#define PTI_LANGUAGE_ENGLISH 17
#define PTI_LANGUAGE_RUSSIAN 18
#define PTI_EDITION_MODE 19
#define PTI_ADD_OR_REMOVE 20
#define PTI_BRUSHING 21
#define PTI_FILLING 22
#define PTI_CONTROL_MODE 23
#define PTI_WASD_SPACE_CTRL 24
#define PTI_MOUSE 25
#define PTI_CAMERA_POSITION 26
#define PTI_HORIZONTAL_POSITION 27
#define PTI_FRONT 28
#define PTI_BACK 29
#define PTI_LEFT 30
#define PTI_RIGHT 31
#define PTI_VERTICAL_POSITION 32
#define PTI_TOP 33
#define PTI_MIDDLE 34
#define PTI_BOTTOM 35
#define PTI_FIND_MODEL_STARTING_TEXT 36
#define PTI_COLUMN_NAME 37
#define PTI_SUBMIT_SIZE_CHANGES 38
#define PTI_ÑHOOSE_CUBEWORLD_FOLDER 39
#define PTI_TO_CONFIRM_CHANGES_PLEASE_RESTART 40
#define PTI_EXTENDED_AXIS 41
#define PTI_AXIS_SIZE_MODEL 42
#define PTI_AXIS_ENDLESS 43
#define PTI_TO_CONVERT_BMP_NEED_24_DEPTH_COLOR 44
#define PTI_MESSAGEBOX_INFO 45
#define PTI_INFO 46
#define PTI_PROGRAM_MODE 47
#define PTI_PROGRAM_TYPE_EMPTY 48
#define PTI_PROGRAM_TYPE_CUBE_WORLD 49
#define PTI_ROTATE_MODEL_AROUND_X_CLOCKWISE 50
#define PTI_ROTATE_MODEL_AROUND_Y_CLOCKWISE 51
#define PTI_ROTATE_MODEL_AROUND_Z_CLOCKWISE 52
#define PTI_ROTATE_MODEL_AROUND_X_COUNTERCLOCKWISE 53
#define PTI_ROTATE_MODEL_AROUND_Y_COUNTERCLOCKWISE 54
#define PTI_ROTATE_MODEL_AROUND_Z_COUNTERCLOCKWISE 55
#define PTI_ROTATE_MODEL 56
#define PTI_FROM_AUTHOR 57
#define PTI_CONTROL_INFORMATION 58
#define PTI_HOTKEYS_INFORMATION_MESSAGEBOX 59
#define PTI_WORK_WITH_GROUPS_OF_VOXELS 60
#define PTI_EDITING_MODE_MESSAGEBOX 61
#define PTI_EDITING_MODE_INFORMATION 62
#define PTI_COPIED_VOXELS_PREVIEW_SETTING 63
#define PTI_IS_COPIED_VOXELS_PREVIEW 64
#define PTI_IS_COPIED_VOXELS_PREVIEW_TRANSPARENT 65
#define PTI_EXPORT_AS_STL_FILE 66

//#define PTI_

//--------------------------------------------------------------------------------------
// Interface Identifier
//--------------------------------------------------------------------------------------

#define II_SEPARATOR 1
#define II_OPEN_DATABASE 2
#define II_SAVE_MODEL 3
#define II_NEW_MODEL_OUTSIDE_DATABASE 4
#define II_SAVE_MODEL_OUTSIDE_DATABASE 5
#define II_LOAD_MODEL_OUTSIDE_DATABASE 6
#define II_INSERT_MODEL 7
#define II_EXPORT_MODEL 8
#define II_CONVERT_PICTURE_TO_MODEL 9

#define II_OPTIONS 20
#define II_SIZE_OF_MODEL 21
#define II_FRAME 22
#define II_WIREFRAME 23
#define II_RESTORE_VIEW 24
#define II_PIPETTE 25
#define II_LANGUAGE 26
#define II_LANGUAGE_ENGLISH 27
#define II_LANGUAGE_RUSSIAN 28

#define II_EDITION_MODE 40
#define II_ADD_OR_REMOVE 41
#define II_BRUSHING 42
#define II_FILLING 43

#define II_CONTROL_MODE 50
#define II_WASD_SPACE_CTRL 51
#define II_MOUSE 52

#define II_CAMERA_POSITION 60
#define II_HORIZONTAL_POSITION 61
#define II_FRONT 62
#define II_BACK 63
#define II_LEFT 64
#define II_RIGHT 65
#define II_VERTICAL_POSITION 66
#define II_TOP 67
#define II_MIDDLE 68
#define II_BOTTOM 69

#define II_SEARCH_TEXT_FIELD 80
#define II_SEARCH_BUTTON_RESET 81
#define II_SEARCH_BUTTON_FIND 82
#define II_INCREMENT_X 83
#define II_INCREMENT_Y 84
#define II_INCREMENT_Z 85
#define II_DECREMENT_X 86
#define II_DECREMENT_Y 87
#define II_DECREMENT_Z 88
#define II_TEXT_FIELD_X 89
#define II_TEXT_FIELD_Y 90
#define II_TEXT_FIELD_Z 91
#define II_SUBMIT_SIZE_CHANGES 92

#define II_EXTENDED_AXIS 93
#define II_AXIS_ENDLESS 94
#define II_AXIS_SIZE_MODEL 95
#define II_MESSAGEBOX_INFO 96
#define II_INFO 97
#define II_PROGRAM_TYPE_EMPTY 98
#define II_PROGRAM_TYPE_CUBE_WORLD 99
#define II_ROTATE_MODEL_AROUND_X_CLOCKWISE 100
#define II_ROTATE_MODEL_AROUND_Y_CLOCKWISE 101
#define II_ROTATE_MODEL_AROUND_Z_CLOCKWISE 102
#define II_ROTATE_MODEL_AROUND_X_COUNTERCLOCKWISE 103
#define II_ROTATE_MODEL_AROUND_Y_COUNTERCLOCKWISE 104
#define II_ROTATE_MODEL_AROUND_Z_COUNTERCLOCKWISE 105
#define II_FROM_AUTHOR 106
#define II_CONTROL_INFORMATION 107
#define II_WORK_WITH_GROUPS_OF_VOXELS 108
#define II_EDITING_MODE_INFORMATION 109
#define II_IS_COPIED_VOXELS_PREVIEW 110
#define II_IS_COPIED_VOXELS_PREVIEW_TRANSPARENT 111
#define II_EXPORT_AS_STL_FILE 112
//#define II_

#endif /*DEFINES*/